version: '3.7'


services:
  delivery:
    image: github.com/anmimos/delivery:latest
    restart: always
    environment:
      - SERVICE_HOST=0.0.0.0  
      - SERVICE_PORT=:80
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=65.108.155.124
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=30432
      - ENVIRONMENT=production
    ports:
      - 8080:80

  client:
    image: github.com/anmimos/jay24:latest
    restart: always
    ports:
      - 3000:80

  admin:
    image: github.com/anmimos/delivery-admin-panel:latest
    restart: always
    ports:
      - 3001:80
  courier:
    image: github.com/anmimos/deliveryegy-courier:latest
    restart: always
    ports:
      - 3002:80
  restaurant:
    image: github.com/anmimos/deliveryegy-restaurant:latest
    restart: always
    ports:
      - 3003:80

